### ISSUE TITLE
Improve styles

### ISSUE THREAD

**Issue by buzz-js** [buzz-js/tic-tac-toe-online#1]
Now it has very basic styles, and it is looking for something a little more striking when playing

**Comment by Tejas99999** [comment]
is this game working. i cloned it but it is not working.

**Comment by buzz-js** [comment]
> is this game working. i cloned it but it is not working.

Have you run `npm install`?

I have tested it and it works correctly

**Comment by Tejas99999** [comment]
![image](https://user-images.githubusercontent.com/59287568/94989352-bd582780-0591-11eb-8ae3-665e38e7ab94.png)
yes i installed the dependencies. But it does not respond after first move

**Comment by buzz-js** [comment]
> ![image](https://user-images.githubusercontent.com/59287568/94989352-bd582780-0591-11eb-8ae3-665e38e7ab94.png)
> yes i installed the dependencies. But it does not respond after first move

You must open a second tab to play with the second player

**Comment by FajarSJ** [comment]
Hi @buzz-js, can i contribute to improve the styling for this?

**Comment by buzz-js** [comment]
@FajarSJ @Tejas99999 You must collaborate with each other

**Comment by FajarSJ** [comment]
That will be awesome @buzz-js, 

Hi @Tejas99999 i will revamp the layout to make it look nicer and you make the striking or animated when user play/win the tic tac toe how about that?

**Comment by buzz-js** [comment]
> Now it has very basic styles, and it is looking for something a little more striking when playing

**Comment by FajarSJ** [comment]
I already make a PR for the improvement, can you please kindly check it @buzz-js @Tejas99999,

here's the link to the PR : https://github.com/buzz-js/tic-tac-toe-online/pull/3

**Comment by buzz-js** [comment]
> I already make a PR for the improvement, can you please kindly check it @buzz-js @Tejas99999,
> 
> here's the link to the PR : #3

Thank you!
